### ISSUE TITLE
from utils.singly_linked_list import SinglyLinkedList

### ISSUE THREAD

**Issue by freecui** [wangy8961/python3-algorithms#1]
树的存储中孩子表示法中utils.singly_linked_list这个是调用的python系统包？还是你自己写的一个包？

**Comment by wangy8961** [comment]
自己写的模块： https://github.com/wangy8961/python3-algorithms/blob/master/2.%20%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%20-%20Data%20Structures/4.%20%E6%A0%91%20-%20Tree/1.%20%E6%A0%91%E7%9A%84%E4%B8%89%E7%A7%8D%E5%AD%98%E5%82%A8%E6%96%B9%E5%BC%8F/utils/singly_linked_list.py
